import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import { ThemeProvider } from "next-themes";
import { Toaster } from "sonner";
import { FooterSection } from "@/components/Footer";
import { GlobalLoadingProvider } from "@/components/GlobalLoadingProvider";
import { Suspense } from "react";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PlayerHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden
        `}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
          >
          <Suspense fallback={<div>Loading...</div>}>
            <GlobalLoadingProvider>
              <div className="flex min-h-screen flex-col justify-between">
                <Nav />
                <div>{children}</div>
                <FooterSection />
              </div>
              <Toaster position="top-right" richColors />
            </GlobalLoadingProvider>
          </Suspense>
        </ThemeProvider>
      </body>
    </html>
  );
}
